/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from JustEatCodeTestWeb.Models.RestaurantViewJsonModel **/
    export interface RestaurantViewJsonModel {
        Id: number;
        Name: string;
        Rating: number;
        CusineTypes: any;
        LogoUrl: string;
    }
}
